kind: StorageClass 
apiVersion: storage.k8s.io/v1 
metadata: 
  name: efs-sc 
provisioner: efs.csi.aws.com 
parameters: 
  provisioningMode: efs-ap 
  fileSystemId: fs-06111dc28f58731e7
  directoryPerms: "777" 
  gidRangeStart: "1000" # optional 
  gidRangeEnd: "2000" # optional 
  basePath: "/dynamic_provisioning" # optional 
