apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sonarqube
  name: sonar-pvc
  namespace: sonar
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
