apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonar
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 9000
   
  selector:
    app: sonarqube
  type: NodePort
